import type { ReactNode } from "react"
import { useCallback } from "react"
import { Pipeline, type PipelineCallback } from "../Pipeline/Pipeline"
import { applyGrayscale } from "./Grayscale"
import { applyLIC } from "./LIC"
import { applyPosterize } from "./Posterize"

/* eslint-disable @typescript-eslint/no-non-null-assertion */

const DEFAULT_BANDS = 4
const DEFAULT_ANGLES = [0, Math.PI / 4, Math.PI / 2, (3 * Math.PI) / 4]
const DEFAULT_LENGTH = 20
const DEFAULT_STEP_SIZE = 1.0

/**
 * Build the per-pixel tier index buffer (0..bands-1) by applying Grayscale
 * then Posterize and reading back the quantized R channel. Each pixel's tier
 * value is `Math.round(255 * b / (bands - 1))` for tier index b — matches the
 * Posterize quantization formula exactly.
 */
function computeTierBuffer(pixels: ImageData, bands: number): { tierBuffer: ImageData; tierValues: Array<number> } {
	const grayBuffer = applyGrayscale(pixels, 1)
	const tierBuffer = applyPosterize(grayBuffer, bands)
	const tierValues: Array<number> = []
	const denom = Math.max(1, bands - 1)

	for (let bandIdx = 0; bandIdx < bands; bandIdx++) {
		tierValues.push(Math.round((255 * bandIdx) / denom))
	}

	return { tierBuffer, tierValues }
}

/**
 * Constant-angle hatching. Bands the source image into `bands` tonal tiers
 * (Grayscale → Posterize) and overlays a per-band line pattern at
 * `angles[b]` with `spacing[b]`. The lightest band draws no lines (pure
 * white). Lines are composited via Multiply, so darker bands accumulate
 * darker hatching. Output preserves the source alpha.
 *
 * Angle convention (matches CSS `linear-gradient`, SVG, and standard graphics
 * tools): `angle=0` produces horizontal lines, `angle=π/2` produces vertical
 * lines, increasing CCW. The angle names the line orientation, not the line
 * normal.
 */
export function applyHatch(
	pixels: ImageData,
	bands: number,
	angles: Array<number>,
	spacing: Array<number>,
): ImageData {
	if (angles.length !== bands) {
		throw new Error(
			`applyHatch: angles.length (${String(angles.length)}) must equal bands (${String(bands)})`,
		)
	}

	if (spacing.length !== bands) {
		throw new Error(
			`applyHatch: spacing.length (${String(spacing.length)}) must equal bands (${String(bands)})`,
		)
	}

	const { width, height, data: src } = pixels
	const { tierBuffer, tierValues } = computeTierBuffer(pixels, bands)
	const tierData = tierBuffer.data

	const output = new Uint8ClampedArray(src.length)

	for (let pixelIdx = 0; pixelIdx < src.length; pixelIdx += 4) {
		output[pixelIdx] = 255
		output[pixelIdx + 1] = 255
		output[pixelIdx + 2] = 255
		output[pixelIdx + 3] = src[pixelIdx + 3]!
	}

	for (let bandIdx = 0; bandIdx < bands - 1; bandIdx++) {
		const tierValue = tierValues[bandIdx]!
		const angle = angles[bandIdx]!
		const bandSpacing = Math.max(1, spacing[bandIdx]!)
		const lineWidth = Math.max(1, bandSpacing * 0.3)
		const cosA = Math.cos(angle)
		const sinA = Math.sin(angle)

		for (let y = 0; y < height; y++) {
			for (let x = 0; x < width; x++) {
				const pixelIdx = (y * width + x) * 4

				if (tierData[pixelIdx]! !== tierValue) continue

				// Standard graphics convention: angle=0 → horizontal lines, angle=π/2 → vertical.
				// `position` measures perpendicular distance to a line through the origin at `angle`.
				const position = y * cosA - x * sinA
				// Use a positive-modulo so negative positions still map onto the stripe.
				const mod = ((position % bandSpacing) + bandSpacing) % bandSpacing

				if (mod < lineWidth) {
					// Multiply by black = 0
					output[pixelIdx] = 0
					output[pixelIdx + 1] = 0
					output[pixelIdx + 2] = 0
				}
			}
		}
	}

	return new ImageData(output, width, height)
}

/**
 * Build a vertical-stripe seed image at the given spacing and line width.
 * Stripes are full-height columns. R=G=B=0 for line columns, 255 elsewhere.
 * Alpha is 255 throughout — alpha is reapplied from source on the final
 * composite.
 */
function buildStripeSeed(width: number, height: number, bandSpacing: number, lineWidth: number): ImageData {
	const data = new Uint8ClampedArray(width * height * 4)
	const period = Math.max(1, bandSpacing)
	const stripe = Math.max(1, lineWidth)

	for (let x = 0; x < width; x++) {
		const isLine = x % period < stripe
		const value = isLine ? 0 : 255

		for (let y = 0; y < height; y++) {
			const pixelIdx = (y * width + x) * 4
			data[pixelIdx] = value
			data[pixelIdx + 1] = value
			data[pixelIdx + 2] = value
			data[pixelIdx + 3] = 255
		}
	}

	return new ImageData(data, width, height)
}

/**
 * Field-aligned hatching. Same banding pipeline as `applyHatch`, but each
 * band's line layer is generated by passing a vertical-stripe seed through
 * `applyLIC` with the supplied `field`. Stripes deform along the field's
 * streamlines, producing engraving-like hatching that follows the underlying
 * direction map.
 *
 * Cost: a full LIC integration runs per band — `O(width * height * length *
 * bands)` sample reads. For `bands=4`, `length=20`, 1080×1080 the cost is on
 * the order of 93M sample reads; acceptable for static demos.
 */
export function applyHatchFieldAligned(
	pixels: ImageData,
	field: ImageData,
	bands: number,
	spacing: Array<number>,
	length: number,
	stepSize: number,
): ImageData {
	if (pixels.width !== field.width || pixels.height !== field.height) {
		throw new Error(
			`applyHatchFieldAligned: pixels and field dimensions must match (pixels=${String(pixels.width)}x${String(pixels.height)}, field=${String(field.width)}x${String(field.height)})`,
		)
	}

	if (spacing.length !== bands) {
		throw new Error(
			`applyHatchFieldAligned: spacing.length (${String(spacing.length)}) must equal bands (${String(bands)})`,
		)
	}

	const { width, height, data: src } = pixels
	const { tierBuffer, tierValues } = computeTierBuffer(pixels, bands)
	const tierData = tierBuffer.data

	const output = new Uint8ClampedArray(src.length)

	for (let pixelIdx = 0; pixelIdx < src.length; pixelIdx += 4) {
		output[pixelIdx] = 255
		output[pixelIdx + 1] = 255
		output[pixelIdx + 2] = 255
		output[pixelIdx + 3] = src[pixelIdx + 3]!
	}

	for (let bandIdx = 0; bandIdx < bands - 1; bandIdx++) {
		const tierValue = tierValues[bandIdx]!
		const bandSpacing = Math.max(1, spacing[bandIdx]!)
		const lineWidth = Math.max(1, bandSpacing * 0.3)

		const seed = buildStripeSeed(width, height, bandSpacing, lineWidth)
		const lineLayer = applyLIC(seed, field, length, stepSize)
		const lineData = lineLayer.data

		for (let y = 0; y < height; y++) {
			for (let x = 0; x < width; x++) {
				const pixelIdx = (y * width + x) * 4

				if (tierData[pixelIdx]! !== tierValue) continue

				// Multiply: out = out * line / 255 per channel
				output[pixelIdx] = Math.round((output[pixelIdx]! * lineData[pixelIdx]!) / 255)
				output[pixelIdx + 1] = Math.round((output[pixelIdx + 1]! * lineData[pixelIdx + 1]!) / 255)
				output[pixelIdx + 2] = Math.round((output[pixelIdx + 2]! * lineData[pixelIdx + 2]!) / 255)
			}
		}
	}

	return new ImageData(output, width, height)
}

/* eslint-enable @typescript-eslint/no-non-null-assertion */

interface HatchProps {
	/** Number of tonal bands. Minimum 2. Default 4. */
	bands?: number
	/** Per-band line angles in radians. Required in constant-angle mode (no `map` prop). Length must equal `bands`. */
	angles?: Array<number>
	/** Per-band line spacing in pixels. Length must equal `bands`. */
	spacing: Array<number>
	/** Field-aligned LIC integration length per direction. Default 20. */
	length?: number
	/** Field-aligned LIC step size in pixels. Default 1.0. */
	stepSize?: number
	map?: ReactNode
	children: ReactNode
}

/**
 * Hatching effect. Bands the source into tonal tiers (Grayscale → Posterize)
 * and renders per-band line layers, multiplied onto a white background. Two
 * modes:
 *
 * - **Constant-angle** (no `map` prop): each band uses a fixed angle and
 *   spacing. Pass `angles` and `spacing` arrays of length `bands`.
 * - **Field-aligned** (with `map` prop): each band's lines integrate along
 *   the supplied vector field via LIC. The map is expected to be a
 *   Direction-style cos/sin/magnitude encoding (see `Direction`).
 *
 * The lightest band draws no lines — it stays pure white. Output preserves
 * the source alpha.
 *
 * @param props
 * @category Effects
 */
export function Hatch({
	bands = DEFAULT_BANDS,
	angles,
	spacing,
	length = DEFAULT_LENGTH,
	stepSize = DEFAULT_STEP_SIZE,
	map,
	children,
}: HatchProps) {
	if (bands < 2) {
		throw new Error(`Hatch: bands must be >= 2 (got ${String(bands)})`)
	}

	if (spacing.length !== bands) {
		throw new Error(
			`Hatch: spacing.length (${String(spacing.length)}) must equal bands (${String(bands)})`,
		)
	}

	if (angles && angles.length !== bands) {
		throw new Error(
			`Hatch: angles.length (${String(angles.length)}) must equal bands (${String(bands)})`,
		)
	}

	const resolvedAngles = angles ?? (bands === DEFAULT_BANDS ? DEFAULT_ANGLES : undefined)

	const effect = useCallback<PipelineCallback>(
		(target, _apply, mapPixels) => {
			if (mapPixels !== undefined) {
				// Field-aligned mode: map prop present, use vector field via LIC
				return applyHatchFieldAligned(target, mapPixels, bands, spacing, length, stepSize)
			}

			// Constant-angle mode: no map prop
			if (!resolvedAngles) {
				throw new Error(
					`Hatch: angles is required in constant-angle mode when bands !== ${String(DEFAULT_BANDS)} (no map prop supplied)`,
				)
			}

			return applyHatch(target, bands, resolvedAngles, spacing)
		},
		[bands, resolvedAngles, spacing, length, stepSize],
	)

	return (
		<Pipeline effect={effect} map={map}>
			{children}
		</Pipeline>
	)
}
